version: '3.4'

services:
  pg:
    image: detoxio/dtxguard:0.1.0
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  demo:
    image: detoxio/dtxguard-demo:0.1.4
    ports:
      - "7860:7860"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DTXPROMPT_GUARD_SVC_URL=${DTXPROMPT_GUARD_SVC_URL}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}

